[litmus]

# this test checks the response headers contain the "Content-Type" header with
# a value of "application/json" then sets the value to "content_type"
[[litmus.test]]
name="index"
method="GET"
url="http://{{.base_service_url}}/get"
[[litmus.test.getters]]
type="head"
path="Content-Type"
exp="application/json"
set="content_type"
