[litmus]

# this test checks the response headers contain the "Content-Type" header with
# a value of "application/json" then sets the value to "content_type"
[[litmus.test]]
name="index"
method="GET"
url="http://{{.base_service_url}}/"
[litmus.test.head]
content_type = {Content-Type="{{.json}}"}
key-1 = "value-1"
[litmus.test.body]
key-2 = "value-2"